name: Tests

on: [push, pull_request]

jobs:
  cargo-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release --all-features
